# Generated by Django 6.0.4 on 2026-04-26 17:22

import imaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0002_scan_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='confdence',
            new_name='confidence',
        ),
        migrations.AlterField(
            model_name='scan',
            name='image',
            field=models.ImageField(upload_to='scans/'),
        ),
    ]
