# Generated by Django 6.0.4 on 2026-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0003_rename_confdence_report_confidence_alter_scan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
